name: ${project.name}
main: vg.civcraft.mc.redditassociation.RedditAssociationPlugin
version: ${project.version}
author: Rourke750
depends: [NameLayer, CivModCore]
commands:
 addreddit:
  aliases: [ar]
 addredditcode:
  aliases: [arc]
 getreddit:
  aliases: [gr]